### ISSUE TITLE
How to set env

### ISSUE THREAD

**Issue by jingxu2021** [rabbitmq/ra-kv-store#9]
### Describe the bug

Thanks for this example.
This erlang app requires some env variables, for example, application:get_env(ra_kv_store, nodes). Could you please suggest how to set these env?

### Reproduction steps

1.source code
2.
3.
...

### Expected behavior

set env variables

**Comment by acogoluegnes** [comment]
There's a configuration example in the Jepsen test: https://github.com/rabbitmq/ra-kv-store/blob/75addee7f974ce38ac16496ccc64bcde6ecda769/jepsen/jepsen.rakvstore/src/main/java/com/rabbitmq/jepsen/Utils.java#L74-L92.

If you decompress the archive file in e.g. `/opt/rakvstore`, the configuration must be `/opt/rakvstore/releases/1/sys.config`.
